
-- Maila's General Merchandise - Supabase production database
-- Run this entire script once in Supabase SQL Editor.

create table if not exists public.products (
  id text primary key,
  name text not null,
  category text default 'Uncategorized',
  srp numeric(12,2) default 0,
  price numeric(12,2) default 0,
  quantity integer default 0 check (quantity >= 0),
  reorder_level integer default 5 check (reorder_level >= 0),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.transactions (
  id text primary key,
  transaction_date timestamptz default now(),
  total numeric(12,2) not null,
  cash numeric(12,2) not null,
  change numeric(12,2) not null
);

create table if not exists public.transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id text references public.transactions(id) on delete cascade,
  product_id text references public.products(id),
  product_name text not null,
  price numeric(12,2) not null,
  quantity integer not null check (quantity > 0)
);

-- Keep updated_at current.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products
for each row execute function public.set_updated_at();

-- Secure database access: users must be signed in.
alter table public.products enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;

drop policy if exists "authenticated products" on public.products;
create policy "authenticated products" on public.products
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated transactions" on public.transactions;
create policy "authenticated transactions" on public.transactions
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated transaction items" on public.transaction_items;
create policy "authenticated transaction items" on public.transaction_items
for all to authenticated using (true) with check (true);

-- Atomic sale processor.
-- The database locks each product row, checks stock, deducts stock,
-- creates the transaction and its items, and returns the receipt.
create or replace function public.complete_sale(p_items jsonb, p_cash numeric)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_tx_id text;
  v_total numeric(12,2) := 0;
  v_change numeric(12,2);
  item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_price numeric(12,2);
  v_name text;
  v_items jsonb := '[]'::jsonb;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in.';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Cart is empty.';
  end if;

  if p_cash is null or p_cash < 0 then
    raise exception 'Invalid cash amount.';
  end if;

  for item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := (item->>'quantity')::integer;
    if v_qty is null or v_qty <= 0 then
      raise exception 'Invalid quantity.';
    end if;

    select * into v_product
    from public.products
    where id = item->>'product_id'
    for update;

    if not found then
      raise exception 'Product not found: %', item->>'product_id';
    end if;

    if v_product.quantity < v_qty then
      raise exception 'Not enough stock for %. Available: %, requested: %',
        v_product.name, v_product.quantity, v_qty;
    end if;

    v_total := v_total + (v_product.price * v_qty);
  end loop;

  if p_cash < v_total then
    raise exception 'Payment is insufficient. Total: %, Cash: %', v_total, p_cash;
  end if;

  v_change := p_cash - v_total;
  v_tx_id := 'R-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS');

  insert into public.transactions(id,total,cash,change)
  values(v_tx_id,round(v_total,2),round(p_cash,2),round(v_change,2));

  for item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := (item->>'quantity')::integer;

    select * into v_product
    from public.products
    where id = item->>'product_id'
    for update;

    update public.products
    set quantity = quantity - v_qty
    where id = v_product.id;

    insert into public.transaction_items(transaction_id,product_id,product_name,price,quantity)
    values(v_tx_id,v_product.id,v_product.name,v_product.price,v_qty);

    v_items := v_items || jsonb_build_array(
      jsonb_build_object(
        'id',v_product.id,
        'name',v_product.name,
        'price',v_product.price,
        'qty',v_qty
      )
    );
  end loop;

  return jsonb_build_object(
    'id',v_tx_id,
    'date',now(),
    'total',round(v_total,2),
    'cash',round(p_cash,2),
    'change',round(v_change,2),
    'items',v_items
  );
end;
$$;

grant execute on function public.complete_sale(jsonb,numeric) to authenticated;

-- Enable Realtime for live inventory/transaction refreshes.
do $$
begin
  begin
    alter publication supabase_realtime add table public.products;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.transactions;
  exception when duplicate_object then null;
  end;
end $$;
