
-- Supabase/PostgreSQL schema for Maila's General Merchandise
create table if not exists products (
  id text primary key,
  name text not null,
  category text default 'Uncategorized',
  srp numeric(12,2) default 0,
  price numeric(12,2) default 0,
  quantity integer default 0,
  reorder_level integer default 5,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists transactions (
  id text primary key,
  transaction_date timestamptz default now(),
  total numeric(12,2) not null,
  cash numeric(12,2) not null,
  change numeric(12,2) not null
);

create table if not exists transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id text references transactions(id) on delete cascade,
  product_id text references products(id),
  product_name text not null,
  price numeric(12,2) not null,
  quantity integer not null
);

alter table products enable row level security;
alter table transactions enable row level security;
alter table transaction_items enable row level security;

-- For production, replace these demo policies with authenticated-user policies.
create policy "authenticated products" on products for all to authenticated using (true) with check (true);
create policy "authenticated transactions" on transactions for all to authenticated using (true) with check (true);
create policy "authenticated transaction items" on transaction_items for all to authenticated using (true) with check (true);
